version: '3.8'
services:
    php-apache-environment:
        container_name: php-apache
        image: php:7.3-apache
        build:
            context: ./dockfile
            
        depends_on:
            - db
        volumes:
            - ./dockfile/app:/var/www/html/
        ports:
            - 8000:80
    
    db:
        container_name: db
        image: mysql:latest
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: mysql
            MYSQL_DATABASE: manege_db
            MYSQL_USER: mysqlUsr
            MYSQL_PASSWORD: superSecurePassword
        ports:
          - "9906:3306"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
          - '8080:80'
        restart: always
        environment:
            PMA_HOST: db
        depends_on:
          - db